server.port=8090

#MySql Configuration
spring.datasource.name = onlineproctoring
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

#Hibernate Config
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

#JWT Config
jwt.TokenExpiry = 30
jwt.SecretKey = TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

#OAuth Config
oauth.clientId=